---
- name: Provision hosts.
  hosts: all
  become: true

  tasks:
    - name: Ensure chrony is installed.
      ansible.builtin.dnf:
        name: chrony
        state: latest

    - name: Ensure chrony is running.
      ansible.builtin.service:
        name: chronyd
        state: started
        enabled: true
