---
- name: Managing software and subscriptions.
  hosts: machine1
  become: true

  tasks:
    - name: Upgrade packages.
      ansible.builtin.dnf:
        name: "*"
        state: latest # noqa package-latest

    - name: Ensure Example repo exists
      ansible.builtin.yum_repository:
        file: example
        name: example-internal
        description: Example Inc. materials
        baseurl: http://materials.example.com/yum/repo
        enabled: true
        gpgcheck: true
        state: present
