# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9"
  #config.vm.box = "palekiwi/rhel9.1"
  #config.vm.box = "generic/ubuntu2004"

  config.ssh.insert_key = false

  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Machines
  MACHINES = 1
  
  (1..MACHINES).each do |machine_id|
    config.vm.define "machine#{machine_id}" do |machine|

      machine.vm.network "private_network", ip: "192.168.77.#{20+machine_id}"

      if machine_id == 1
        machine.vm.hostname = "control"

        machine.vm.provider :libvirt do |libvirt|
          libvirt.memory = 1024
          libvirt.cpus= 2
        end
      else
        machine.vm.hostname = "machine#{machine_id}"

        machine.vm.provider :libvirt do |libvirt|
          libvirt.memory = 256
          libvirt.cpus = 1
        end
      end
  
      # Only execute once the Ansible provisioner,
      # when all the machines are up and ready.
      if machine_id == MACHINES
        machine.vm.provision :ansible do |ansible|
          # Disable default limit to connect to all the machines
          ansible.limit = "all"
          ansible.playbook = "playbooks/provision.yml"

          if MACHINES > 1
            ansible.groups = {
              "app" => ["machine[2:#{MACHINES}]"]
            }
          end
        end
      end
    end
  end

end
